#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Converts djvu file $1 to a pdf file.
#
# The pdf is generated in the same directory and name as the pdf, but with extension pdf instead of djvu.
# The extension .djvu is optional, as specified by opt-ext
#
# DEPENDENCIES
#
#   sudo apt-get install djvulibre-bin libdjvulibre21 okular-extra-backends evince libevdocument1 libevview1
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: djvu-to-pdf djvupath-opt-ext

EXAMPLE

djvu-to-pdf asdf
djvu-to-pdf asdf.djvu
' 1>&2
}

# fixed nargs checking:
if [ $# -ne 1 ]
then
  usage
  exit 1
fi

DJVU_RELPATH="$( opt-ext "$1" djvu )"
PDF_RELPATH="$(basename-noext "$DJVU_PATH").pdf"
ddjvu -format=pdf "$DJVU_PATH" "$PDF_RELPATH"

exit 0

