#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Converts djvu file $1 to a pdf file.
#
# The pdf is generated in the same directory and name as the pdf, but with extension pdf instead of djvu.
#
#   sudo apt-get install 
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'djvu-to-pdf "$djvu"


INSTALL UBUNTU

    sudo aptitude install djvulibre-bin
  
EXAMPLE

    djvu-to-pdf a.djvu
      generates a.pdf
' 1>&2
}

# fixed nargs checking:
if [ $# -ne 1 ]
then
  usage
  exit 1
fi

DJVU_PATH="$1"
PDF_PATH="$(basename-noext "$DJVU_PATH").pdf"
ddjvu -format=pdf "$DJVU_PATH" "$PDF_PATH"

exit 0

