#!/usr/bin/env bash

#!install_requires="sudo apt-get install realpath"
#!install_requires="cd \"$SOMEWHERE_IN_YOUR_PATH\"; wget https://github.com/cirosantilli/bash/blob/48dd9d10f7d094291b246b02a6b08fc650e81e2d/find-music"

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: find-music-make-m3u [options] find-root...

DEPENDENCIES

  sudo apt-get install realpath
  wget https://github.com/cirosantilli/bash/blob/48dd9d10f7d094291b246b02a6b08fc650e81e2d/find-music

SAMPLE CALLS

  find-music-make-m3u .
  find-music-make-m3u /tmp /bin
  find-music-make-m3u -o out.m3u .
  find-music-make-m3u -a .
  find-music-make-m3u -r -o all.m3u .

  finds music under given input dir based on file extension,
  makes an m3u list out of them.

  If no music files are found, no m3u is created.

OPTIONS

  * -a: Absolute. If given paths on m3u are absolute, otherwise
  paths are relative by default. Obviously, if you plan on moving
  your m3u around YOUR system, you have to give it absolute paths.
  but if you plan on giving them to someone else, relative paths 
  are the way to go.

  * -o: Specify output relative or absolute. If ommited in non
  recursive mode, the output is put on standard output. If in re
  cursive mode, the output always goes to a file, and 
  this allows to change the default filename all.m3u.

  * -r: Recursive. If specified, for each directory makes an
  m3u of all the music under that directory. If the output name
  is not given, then the music lists are saved to default name
  'all.m3u'. The output is always put inside a files, never to
  standard output.

LIMITATIONS

  No newlines in names!
' 1>&2

}

#check dependencies
if -n which realpath &> /dev/null; then
    echo "realpath not found. To install on Ubuntu use:" 1>&2
    echo "sudo apt-get install realpath" 1>&2
    exit 1
fi

if -n which find-music &> /dev/null; then
    echo "find-music not found. To install:" 1>&2
    echo "wget -P ~/bin https://github.com/cirosantilli/bash/raw/48dd9d10f7d094291b246b02a6b08fc650e81e2d/find-music" 1>&2
    exit 1
fi

# default vals
RECURSE=false
FILE_OUTPUT=false
OUTPUT_PATH="all.m3u"
ABSOLUTE=false

while getopts ao:r OPT; do
  case "$OPT" in
    a)
      ABSOLUTE=true
      ;;
    h)
      usage
      exit 0
      ;;
    o)
      OUTPUT_PATH=$OPTARG
      FILE_OUTPUT=true
      ;;
    r)
      RECURSE=true
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done

shift `expr $OPTIND - 1`

# ensure at least one param left
if [ $# -eq 0 ]; then
  usage
  exit 1
fi

if $RECURSE; then
  for ROOT in "$@"; do
    ABS_ROOT="$( realpath "$ROOT")"
    find "$ROOT" -type d -print0 | while read -d '' DIR
    do
      cd "$DIR"
      find-music-make-m3u -o "$OUTPUT_PATH" . 
      cd "$ABS_ROOT"
    done 
  done
else

  if $ABSOLUTE; then
    ABS_PATHS=()
    for REL_PATH in "$@"; do
      ABS_PATHS+=( "$( realpath "$REL_PATH" )" )
    done
    OUTPUT="$(find-music "${ABS_PATHS[@]}" | xargs -0 -I '{}' echo "{}")"
  else
    OUTPUT="$(find-music "$@" | xargs -0 -I '{}' echo "{}")"
  fi

  # don't make empty m3u
  if [ ! -z "$OUTPUT" ]; then

    # sort
    OUTPUT="$( echo "$OUTPUT" | sort )"

    if $FILE_OUTPUT; then
      echo "$OUTPUT" > "$OUTPUT_PATH"
    else
      echo "$OUTPUT"
    fi

  fi

fi

exit 0
