#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# prints null char (\0) separated list of music files
#
# where to look follows the same interface as find: for current
# dir you must put the '.', and you can just add as many locations as you want
#
# music files are recognized from their extension 
# 
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: find-music find-root ...' 1>&2
}

# check input
if [ $# -eq 0 ]
then
  usage
  exit 1
fi

find "$@" -type f \( -iname "*.mp3" -o -iname "*.flac" -o -iname "*.m4a"  -o -iname "*.ogg" -o -iname "*.wav" -o -iname "*.wma" -o -iname "*.au" -o -iname "*.ape" \) -print0

exit 0
