#!/usr/bin/env bash

#if one arg, uses it as message, if no args commists without message

if [ $# -eq 1 ]; then
  git commit -am "$1"
else
  git commit -a --allow-empty-message -m ''
fi

git push github master #one step commit push

exit 0
