#!/usr/bin/env bash

# start a repository here and add all files with given extension to it. 
# does not look inside hidden folders

if [ ! $# -eq 1  ] 
then
	echo "Usage: command-name extension-to-git-add"
fi

git init

if [ $1 != "sh" && $1 != "bash" ]
then
	find . -path "./.*" -prune -o -name '*.$1' -exec git add "{}" +
else # for bash scripts
	find-bash-scripts | xargs -0 git add
fi
fin
git commit -a -m 'first commit'
git config --global user.name "Ciro Duran Santilli"
git config --global user.email ciro.santilli@gmail.com
git remote add github https://github.com/cirosantilli/latex.git
git push github
