#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Apt-get installs all the dependencies that did not come
# with my Ubuntu 12.04 and which are necessary to run this library.
#
#------------------------------------------------------------

# expands paths to full paths. like python abspath
sudo apt-get install realpath

# if you want to do djvu conversion
sudo apt-get install djvulibre-bin libdjvulibre21 okular-extra-backends evince libevdocument1 libevview1
