#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Compile latex > pdf and open it in Okular.
#
# All output and auxiliary files are created on the same dir as the tex file.
# If an Okular instance is already open, the pdf file is reloaded. 
#
# Synctex and bibtex are used. 
#
# This is a rather simple command, and should be overseeded by proper synctex syncing in pdf editors.
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command returns error

usage()
{
  echo "Usage: latex-pdf-okular tex-path [tex-line]" 1>&2
}

if [ $# -eq 0 ]
then
  usage
  exit 1
fi
INPUT_PATH_NOEXT="$( basename-noext "$1" )"

if [ $# -gt 1 ]
then
  TEX_LINE="$2"
else
  TEX_LINE=""
fi

if [ $# -gt 2 ]
then
  usage
  exit 1
fi

# make pdf with bibtex and synctex
latex-to-pdf "$INPUT_PATH_NOEXT"

# view
OUTPUT_PATH="$INPUT_PATH_NOEXT".pdf
if [ -z "$TEX_LINE" ]
then
  okular --unique "$OUTPUT_PATH" &
else
  PDF_PAGE="( synctex-forward "$TEX_LINE" )"
  okular --unique -p "$PDF_PAGE" "$OUTPUT_PATH" &
fi

exit 0
