#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Compile latex > pdf and open it in Okular.
#
# All output and auxiliary files are created on the same dir as the tex file.
# If an Okular instance is already open, the pdf file is reloaded. 
#
# Synctex and bibtex are used. 
#
# This is a rather simple command, and should be overseeded by proper synctex syncing in pdf editors.
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command returns error

usage()
{
  echo "Usage: latex-pdf-okular tex-path [tex-line]" 1>&2
}

# parameter parsing

# obligartory params;
if [ $# -gt 0 ]; then
  INPUT_PATH_NOEXT="$( basename-noext "$1" )"
  shift
else
  usage
  exit 1
fi

# optional params

TEX_LINE=""

if [ $# -gt 0 ]; then
  TEX_LINE="$1"
  shift
fi

# too many params
if [ $# -gt 0 ]; then
  usage
  exit 1
fi

# main
AUX_DIR="./tmp/"
PDF_DIR="./"
TEX_DIR="./"

# make pdf with bibtex and synctex
latex-to-pdf "$INPUT_PATH_NOEXT" "$AUX_DIR" "$PDF_DIR"

# view
OUTPUT_PATH="$INPUT_PATH_NOEXT".pdf
if [ -z "$TEX_LINE" ]; then
  okular --unique "$OUTPUT_PATH" &
else
  PDF_PAGE="( synctex-forward -t "$TEX_DIR" -p "$PDF_DIR" "$TEX_LINE" )"
  #PDF_PAGE="( synctex-forward -t "$TEX_DIR" -s "$AUX_DIR" -p "$PDF_DIR" "$TEX_LINE" )"
  okular --unique -p "$PDF_PAGE" "$OUTPUT_PATH" &
fi

exit 0
