#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# 
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: latex-pdf-view tex-file-opt-ext'
}

# fixed nargs checking
if [ $# -ne 1 ]
then
  usage
  exit 1
else
  echo here
  TEX_PATH="$( opt-ext "$1" tex )"
  echo here
  pdflatex -synctex=1 $TEX_PATH
  exit 0
fi
