#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
#------------------------------------------------------------

# unpack
tar xvzf package.tar.gz (or tar xvjf package.tar.bz2)
cd package

# configure
./configure
# MANUAL: edit/rename some config files

# build
make

# install
sudo install # needs sudo because you are going to move things to folders like /usr or /usr/local

# This moves the files you have built, and which were located under the same current folder (typically ./bin) to their final destinations. There are quite a few final destinations, but the most common destination roots are:
#
# usr/
# usr/local
# opt/ # less common than the others
#
# Inside those root locations, typical file structures are:
#
# ./bin  contains the binaries to be run, usr/bin and usr/local/bin are probably in your path
# ./lib  contais the application data, such as your saved program preferences, images used in GUIs, etc

# clean
make clean # this cleans the .o and binaries created in the current folder after they have been moved to their final destinations with make install.
