#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# If $1 file in cur dir, print it and return 0.
# Else if $1$2 is a file in cur dir, print it and return 0.
# Else, print nothing and return 1.
# 
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo "Usage: opt-ext basename-noext ext-nodot

EXAMPLE:

opt-ext report tex
opt-ext report.tex tex
opt-ext nonexistent tex
"
}

# fixed nargs checking:
if [ ! $# -eq 2 ]
then
  usage
  exit 1
else

  if [ -f "$1" ]
  then
    echo "$1"
    exit 0
  fi
  
  if [ -f "${1}.${2}" ]
  then
    echo "${1}.${2}"
    exit 0
  fi

  exit 1
fi
