#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Removes extension (as gotten by ext-nodot) from given path.
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
echo "Usage: path-noext path}

if [ $# -ne 1 ]
then
  usage
  exit 1
else
  INPUT_PATH=$1
  EXT_NODOT="$(ext-nodot "$INPUT_PATH")"

  # extract the extension from the end
  echo "${INPUT_PATH%%."$EXT_NODOT"}"
fi

exit 0
