#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Convenient wrapper for sha1sum.
#
# Does multiple files and outputs the sums only,
# newline separated
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: sha1sum-get path ...' 1>&2
}

# check input
if [ $# -eq 0 ]
then
  usage
  exit 1
fi

for F in "$@"; do
  echo "$( sha1sum "$F" | awk -F ' ' '{ print $1 }' )"
done

exit 0
