#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# 
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  local n=`tput sgr0` # normal
  local b=`tput bold` # bold
  local i=`tput ital` # bold
  echo "${b}Usage${n}: tar-encrypt dir [...]" 1>&2
}

# argument parsing

# assert at least one left
if [ $# = 0 ]; then
  usage
  exit 1
fi

# main part
read -s -p "Password for all paths: " PASS
for F in "$@"; do
  TTAR="$(mktemp)"
  tar cf "$TTAR" "$F"
  TIME_STAMP=`date "+%Y-%m-%d %H-%M-%S"`
  gpg --passphrase "$PASS" -o "$F $TIME_STAMP" -c "$TTAR"
  rm "$TTAR"
done

exit 0
