#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# 
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: ' 1>&2
}

# argument parsing

# get first arg
if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi

# get second arg
if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi

# assert at least one left
if [ $# = 0 ]; then
  usage
  exit 1
fi

# main part
for in "$@"; do

done

exit 0
