#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Template for positional arguments
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: ' 1>&2
}

if [ $# -eq 0 ]
then
  usage
  exit 1
fi
="$1"

if [ $# -gt 1 ]
then
  ="$2"
else
  =""
fi

if [ $# -gt 2 ]
then
  usage
  exit 1
fi

exit 0
