#!/usr/bin/env bash

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'USAGE

  

SUMMARY



SAMPLE CALLS



OUTPUT



SIDE EFFECTS



AUTHORS

  Ciro D. Santilli
' 1>&2
}

#check dependencies
if -n which <command> &> /dev/null; then
    echo "<command> not found. To install on Ubuntu use:" 1>&2
    echo "sudo apt-get install <command>" 1>&2
    exit 1
fi

if -n which <command> &> /dev/null; then
    echo "<command> not found. To install:" 1>&2
    echo "wget -P ~/bin <url>" 1>&2
fi

#check arguments
if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi



exit 0
