#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# 
#
#------------------------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'Usage: ' 1>&2
}

# argument parsing

# obligatory arguments
if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi

if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi



exit 0
