#!/usr/bin/env bash

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

usage()
{
  echo 'USAGE

  

SUMMARY



DESCRIPTION



INSTALLATION



TIPS



CAVEATS



OUTPUT



SIDE EFFECTS



TODO



SAMPLE CALLS



AUTHORS

  Ciro Duran Santilli
' 1>&2
}

#check dependencies
if -n which <command> &> /dev/null; then
  echo "<command> not found. To install on Ubuntu use:" 1>&2
  echo "sudo apt-get install <command>" 1>&2
  exit 1
fi

if -n which <command> &> /dev/null; then
  echo '<command> not found. To install:
  DIR_IN_PATH=~/bin
  OUT="$DIR_IN_PATH"/<command>
  wget -nc -O "$OUT" <url> && \
  chmod +x "$OUT"'
fi

#check arguments
if [ $# -gt 0 ]; then
  ="$1"
  shift
else
  usage
  exit 1
fi

#there must be no args left
if [ $# -gt 0 ]; then
  usage
  exit 1
fi

#there must still be args left
if [ $# -eq 0 ]; then
  usage
  exit 1
fi

for in "$@"; do

done

exit 0
