#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
#
#------------------------------------------------------------

set -u
set -e

usage()
{
  echo 'Usage: ' 1>&2
}

# default vals
FLAG=false

while getopts hvfi:o: OPT; do
  case "$OPT" in
    h)
      usage
      exit 0
      ;;
    f)
      FLAG=true
      ;;
    i)
      INPUT_PATH=$OPTARG
      ;;
    o)
      OUTPUT_PATH=$OPTARG
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done

shift `expr $OPTIND - 1`

# ensure at least one param left
if [ $# -eq 0 ]; then
  usage
  exit 1
fi

for in "$@"
do

done

exit 0
