#!/usr/bin/env bash

#------------------------------------------------------------
#
# Ciro D. Santilli 
#
# Used to check if this folder is in the path or not. 
#
#------------------------------------------------------------

# immediate:
echo TEST
