#!/usr/bin/env bash

#------------------------------------------------
#
# Ciro D. Santilli
#
# This script contains all the software that I would 
# install on a fresh ubuntu to turn it into a powerhouse.
#
# I hope this will:
#
# * serve as a way to quickly reinstall everything if I ever have to reinstall ubuntu again (it does happen, believe me)
# * constitute useful software collection and installation procedures suggestion for others
#
#-------------------------------------------

set -u # error on undefined variable
set -e # stop execution if one command goes wrong

firefoxdownloadfolder="~/nobackup/download"

# update
  sudo apt-get update && sudo apt-get upgrade

# interface tweaking

  # ubuntu tweak
  sudo add-apt-repository ppa:tualatrix/ppa
  sudo apt-get update 
  sudo apt-get install ubuntu-tweak

  sudo apt-get install myunity

# proprietary
  sudo -E wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list
  sudo apt-get --quiet update
  sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring
  sudo apt-get --quiet update
  sudo apt-get install app-install-data-medibuntu apport-hooks-medibuntu

  # codecs # ERROR: mpg123libjpeg-progs cannot locate
  # use TAB to navigate msfonts
  sudo apt-get install non-free-codecs libxine1-ffmpeg gxine mencoder totem-mozilla icedax tagtool easytag id3tool lame nautilus-script-audio-convert libmad0 mpg321 mpg123libjpeg-progs

  # skype
  firefox http://www.skype.com/intl/en-us/get-skype/on-your-computer/linux/downloading.ubuntu32
  nautilus $firefoxdownloadfolder
  # Win > startup applications > bash -c "sleep 10 && skype" # must sleep, or interface broken

  sudo apt-get install pidgin

  # media
  sudo apt-get install vlc

# document viewing and converting

  # okular
  sudo apt-get install okular

  # calibre
  sudo apt-get install calibre
  cd ~
  mkdir nobackup/calibre
  # set library there: Cntr p > ...

  # djvu
  # good djvu reader
  sudo apt-get install djview4
  # for djvu conversion
  sudo apt-get install djvulibre-bin libdjvulibre21 okular-extra-backends evince libevdocument1 libevview1 libtiff-tools
  # to convert djvu pdf, to ddjvu -format=pdf in out

# file sharing

  # torrent deluge
  sudo add-apt-repository ppa:deluge-team/ppa
  sudo apt-get update
  sudo apt-get install deluge

  # soulseek client nicotine+ 
  sudo apt-get install nicotine+

  sudo apt-get install fdupes # fine command line tool for eliminating duplicates by content

  # archieve formats
  sudo apt-get install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack lha arj cabextract file-roller

  # dropbox
  noaptget=~/nobackup/noaptget/
  if [ ! -d $noaptget ]; then
    mkdir $noaptget
  fi
  cd $noaptget
  wget -O - "https://www.dropbox.com/download?plat=lnx.x86" | tar xzf -
  ./.dropbox-dist/dropboxd &

# image manipulation

  # gimp
  sudo apt-get install gimp

  # inkscape
  sudo apt-get install inkscape

# programming tools

  # python pip package management
    sudo apt-get install python-pip python-dev build-essential 
    sudo pip install --upgrade pip 
    sudo pip install --upgrade virtualenv 
    #sudo pip install <PACKAGE_NAME> # installs package
    #firefox http://pypi.python.org/pypi?%3Aaction=browse # to get find the package names

  # opengl glut
    sudo apt-get install build-essential
    sudo apt-get install freeglut3-dev

  # eclipse
    sudo apt-get install eclipse # ERROR cdt tools not good

    # MANUAL: install plugins.

    # must be root for those operations so
    gksudo eclipse

    # Help > Install new software > Availabe software sources > Check every single case there!
    # Help > Install new software > New sources

    # add vim like editing to eclipse
    # http://vrapper.sourceforge.net/update-site/stable

    # add eclipe functionality to vim
    # http://vrapper.sourceforge.net/update-site/stable

    # color themes

    # http://eclipse-color-theme.github.com/update
    # 	mine: http://www.eclipsecolorthemes.org/?view=theme&id=7915
    # to install: File > Import > Preferences > Select *.epf (Eclipse menus are SO unintuitive...)

    # c and c++
    # http://download.eclipse.org/tools/cdt/releases/indigo/

    # python
    # http://pydev.org/updates

    # html, javascript, php
    # http://download.eclipse.org/webtools/repository/indigo/

    # latex
    # http://texlipse.sourceforge.net
    # forward search to okular: 
    #    
    #
    # inverse search from okular: Settings > Configure Okular > Editor
    #   Editor: custom text editor,
    #   Command: gvim --remote +%l %f 

  # version control

    # git
    sudo apt-get install git
    sudo apt-get install gitk	# a git graphic local branch viewer
    # not set it up to follow github
    # http://help.github.com/linux-set-up-git/

    # svn subversion
    sudo apt-get install subversion

  # vim

    sudo apt-get install vim
    sudo apt-get install vim-gtk # gvim, runs outside command line, and thus gets around many command line limitations such as reserved shortcuts
    sudo apt-get install exuberant-ctags # to create tags (allows you to jump to definitions for example)

    # get an overpowered distro (will save hours of plugin management)

    # install plugins
    # I prefer to unzip the plugins under .vim, and then add their paths to my .vimrc. This way, if I ever want to remove a plugin, all I need is to remove the folder, and some small code in the vimrc.
    mkdir -p ~./vim
    cd ~/.vim

    # easytags
    # generates a tags file every seconds to that you can jump to tag definitions
    # (functions, variables, etc.) with Cntl + ]
    wget http://peterodding.com/code/vim/downloads/easytags.zip
    unzip easytags.zip
    rm easytags.zip
    echo ":let g:easytags_file = '~/.vim/easytagstags'" >> ~/.vimrc # save tags in ~/.vim/easytagstags insteaed ot the default ~/
    vim

    vim-addons install latex-suite

  # Web design lamp (Linux Apache + Mysqp + PHP)

    #sudo chown "$USER" /var/www/ #not sure it is safe, but good if you are on a test machine

    # from tutorial at: http://community.linuxmint.com/tutorial/view/486
    # apache
    sudo apt-get install apache2
    firefox http://localhost/ & # test apache

    # php
    sudo apt-get install php5 libapache2-mod-php5
    sudo /etc/init.d/apache2 restart
    # test php
    echo '<?php phpinfo(); ?>' | sudo tee /var/www/testphp.php > /dev/null
    firefox http://localhost/testphp.php &

    # mysql
    sudo apt-get install mysql-server
    # he will ask you for the password, fill it in
    # mysql -u root # the tutorial said do that, but I didn't need to. This would be for the password.

    # phpmyadmin
    sudo apt-get install libapache2-mod-auth-mysql php5-mysql phpmyadmin
    # gksudo gedit /etc/php5/apache2/php.ini # according to tutorial, should uncomment ;extension=mysql.so, but I could not find it in the file. still works.

    # make sure 'Include /etc/phpmyadmin/apache.conf' is in the apache config file
    gksudo gedit /etc/apache2/apache2.conf &
    #apacheconf='/etc/apache2/apache2.conf'
    #ensureline='Include /etc/phpmyadmin/apache.conf'
    #grep $ensureline apacheconf && ( echo $ensureline | sudo tee -a $apacheconf > /dev/null )

    sudo /etc/init.d/apache2 restart

   # test mysql
   firefox http://localhost/phpmyadmin & # login: 'root'. password: what you entered at installation.
    

  # publishing

    # pandoc. convert to/from extended markdow / latex / html
    sudo apt-get install pandoc
    sudo apt-get install texlive-fonts-recommended
    # you need this for certain latex fonts such as Continuous functions C

    sudo apt-get install texmaker


# file management

  # krusader
  sudo apt-get install krusader
  sudo apt-get install konqueror # needs to manage bookmarks. (otherwise, button does nothing)
  sudo apt-get install konsole   # needs to terminal emulator. (otherwise, button does nothing)

  # filezilla
  sudo apt-get install filezilla
  sudo apt-get install deluge

  sudo apt-get install gparted
  # gparted. create/delete/change partition size. In order to reduce you windows partition
  # you need first to reduce it in windows, and then use this.

# keyboard and mouse automation 

  # autokey
  sudo apt-add-repository ppa:cdekter/ppa
  sudo apt-get install autokey-gtk

  # xdotool. can send clicks and manage window properties.
  sudo apt-get install xdotool


# command line utilities

  sudo apt-get install realpath
  # resolves relative paths

  sudo apt-get install ack-grep
  # overpowered grepping
